### ISSUE TITLE
고객앱 include_stamp_card.xml 변수 값 에러

### ISSUE THREAD

**Issue by stories2** [kangjisung/AndroidInven#11]
<android.support.design.widget.TabLayout
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:id="@+id/tabLayout"
            android:clickable="false"
            app:tabIndicatorHeight="0dp"
            android:layout_centerInParent="true"
            app:tabPaddingEnd="5dp"
            app:tabPaddingStart="5dp"
            app:tabIndicatorColor="?android:attr/textColorSearchUrl"
            app:tabSelectedTextColor="?android:attr/textColorLinkInverse">
        </android.support.design.widget.TabLayout>
에서
            app:tabIndicatorColor="?android:attr/textColorSearchUrl"
            app:tabSelectedTextColor="?android:attr/textColorLinkInverse">
이 부분의 값을 명확히 해주길 바람

**Comment by thdus1299** [comment]
탭 레이아웃 색상 변경하려다가 실수로 추가된 부분임. 삭제해서 오류해결.
