### ISSUE TITLE
customer-app-layout-design 어플실행중지

### ISSUE THREAD

**Issue by thdus1299** [kangjisung/AndroidInven#12]
맨 처음 빵집사 어플을 실행시킬 때 어플이 켜지지 않고 바로 중지되는 현상

**Comment by stories2** [comment]
이슈 확인중

**Comment by stories2** [comment]
AlertDialog.Builder의 생성자에 context를 넘겨주던걸 activity로 변경 후 픽스
자세한 변경 사항은 커밋 로그를 참조
https://github.com/kangjisung/AndroidInven/commit/2d2bc8e90097ce6aece22a6a3ff59866178565c1
