### ISSUE TITLE
CustomerApp StampFragment Load Problem

### ISSUE THREAD

**Issue by stories2** [kangjisung/AndroidInven#15]
>스탬프 레이아웃 로드 속도 너무 느림
function (int mileage) 형태의 함수를 호출하면 자동으로 자신의 마일리지 상황에 따라서 스탬프 레이아웃이 갱신되도록하는 함수도 추가해주길 바람

**Comment by thdus1299** [comment]
06264097d3646200dccb7eda83a56d05310ecd41
처음 스탬프가 등장하는 화면에서, 로딩이 오래 걸리는 스탬프가 완전히 뜰 동안 Loading 이라는 글자가 떠있도록 수정
