### ISSUE TITLE
매장 등록 오류

### ISSUE THREAD

**Issue by dinsslug** [kangjisung/AndroidInven#21]
## Expected behavior
매장 등록하면 앱 껐다켜도 목록에 남아있어야 함

## Actual behavior
앱 껐다키면 목록에서 사라져 있음

## Steps to reproduce the behavior
Expected behavior 해보면 됨

## Program printed log
```
Input log here
```

**Comment by stories2** [comment]
that issue fixed
c8e7b9e6453f9b9a0c88c36476dd2850edac20b8
