### ISSUE TITLE
컴파일 에러

### ISSUE THREAD

**Issue by stories2** [kangjisung/AndroidInven#9]
빠진 파일로 인해 빌드가 실패해요
mipmap폴더의 아이콘 하나가 빠진듯해요
확인하고 다시 올려주세요

**Comment by stories2** [comment]
layout_rounded_page 에서 @mipmap/rounded_corner가 없어요 확인해주세요
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:gravity="left|top"
        android:drawable="@mipmap/rounded_corner">
    </item>
    <item
        android:gravity="right|top">
        <rotate
            android:pivotX="50%" android:pivotY="50%"
            android:fromDegrees="90" android:toDegrees="0">
            <bitmap android:src="@mipmap/rounded_corner" />
        </rotate>
    </item>
    <item
        android:gravity="right|bottom">
        <rotate
            android:pivotX="50%" android:pivotY="50%"
            android:fromDegrees="180" android:toDegrees="90">
            <bitmap android:src="@mipmap/rounded_corner" />
        </rotate>
    </item>
    <item
        android:gravity="left|bottom">
        <rotate
            android:pivotX="50%" android:pivotY="50%"
            android:fromDegrees="270" android:toDegrees="180">
            <bitmap android:src="@mipmap/rounded_corner" />
        </rotate>
    </item>
</layer-list>

**Comment by thdus1299** [comment]
rounded_corner -> 보내줌
